# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='track_num',
            field=models.BigIntegerField(default=None),
        ),
    ]
