# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230815_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='recipient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Subscriber'),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='status',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='track_num',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
